In [1]:
import numpy as np

a = np.random.rand(5)

In [3]:
print(a)

[0.15330527 0.44178452 0.02146125 0.07231776 0.05606059]


In [4]:
print(a.shape)

(5,)


In [5]:
print(a.T)

[0.15330527 0.44178452 0.02146125 0.07231776 0.05606059]


In [7]:
print(np.dot(a , a.T))

0.22750930321368257


In [8]:
a = np.random.rand(5 , 1)
print(a)

[[0.16437993]
 [0.77478595]
 [0.64725843]
 [0.6382623 ]
 [0.71846151]]


In [10]:
print(a.T)

[[0.16437993 0.77478595 0.64725843 0.6382623  0.71846151]]


In [11]:
print(np.dot(a , a.T))

[[0.02702076 0.12735926 0.1063963  0.10491751 0.11810065]
 [0.12735926 0.60029327 0.50148674 0.49451666 0.55665389]
 [0.1063963  0.50148674 0.41894347 0.41312065 0.46503027]
 [0.10491751 0.49451666 0.41312065 0.40737876 0.4585669 ]
 [0.11810065 0.55665389 0.46503027 0.4585669  0.51618694]]
